### ISSUE TITLE
The demo seem don't work well

### ISSUE THREAD

**Issue by pribadihcr** [sugyan/tensorflow-mnist#2]
Hi @sugyan 

I go the the following message:
npm WARN cannot run in wd tensorflow-mnist@1.0.0 gulp (wd=/home/srin/HandWritten/tensorflow-mnist)

and when I go to 127.0.0.1:8000, the demo don't work well. I

**Comment by sugyan** [comment]
@pribadihcr 
hmm... I think it is npm's permission issue.
please try `npm install --unsafe-perm`.
(ref. http://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd)

**Comment by pribadihcr** [comment]
@sugyan 

Thank you for the reply, I have done. But when I pointed to 127.0.0.1:8000, it seem still don't work properly.

![web](https://cloud.githubusercontent.com/assets/13068286/11390717/56af73c8-937f-11e5-87b9-6707f3ac4460.jpg)

**Comment by sugyan** [comment]
Umm.. it seems that javascript doesn't work.
If `npm install` succeeded, there shold be `static/js/main.js` (this will be generated by `gulp` task). Is it exist?
If `main.js` exists and don't work, some errors may cause in JavaScript. Please check your browser's console output by using such as DevTools.
(ref. https://developer.chrome.com/devtools)

**Comment by pribadihcr** [comment]
@sugyan 

When I did inspect element in canvas draw digit, I got the following error:

Failed to load resource: the server responded with a status of 404 (NOT FOUND) http://127.0.0.1:8000/static/js/main.js

**Comment by sugyan** [comment]
Please try `./node_modules/.bin/gulp`. 
In my environment (node v5.1.0, npm 3.3.12), these messages was output, and created `static/js/main.js` file.
<img width="524" alt="2015-11-25 16 54 47" src="https://cloud.githubusercontent.com/assets/80381/11391349/567b744a-9395-11e5-94a4-935347634603.png">

**Comment by pribadihcr** [comment]
@sugyan 

I am sorry,
I got the following error:

srin@srin:~/HandWritten/tensorflow-mnist$ ./node_modules/.bin/gulp 

/home/srin/HandWritten/tensorflow-mnist/gulpfile.js:6
gulp.task('build', () => {
                    ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/home/srin/HandWritten/tensorflow-mnist/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/home/srin/HandWritten/tensorflow-mnist/node_modules/liftoff/index.js:192:16)
    at module.exports (/home/srin/HandWritten/tensorflow-mnist/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/home/srin/HandWritten/tensorflow-mnist/node_modules/liftoff/index.js:185:9)

**Comment by sugyan** [comment]
I see. Do you use node < v4.0.0?
"arrow function" is supported >= 4.0 (https://nodejs.org/en/blog/release/v4.0.0/).
Sorry I fixed `gulpfile.js`. Please git pull and try again.

**Comment by pribadihcr** [comment]
@sugyan 

I have done.
But got new error through inspect element:

Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode (main.js:2) :(

**Comment by sugyan** [comment]
oh...
Could you tell me your node version and npm version?

```
$ node -v
$ npm -v
```

and tell me your browser and its version.

**Comment by pribadihcr** [comment]
@sugyan 

OMG! my nodejs version is old. 0.10

I did:
curl --silent --location https://deb.nodesource.com/setup_4.x | sudo bash -
sudo apt-get install nodejs

and the demo is work properly.

thanks @sugyan for you help!

**Comment by sugyan** [comment]
You're welcome! thank you for reporting.
