### ISSUE TITLE
src under static/js and static/css may be wrong

### ISSUE THREAD

**Issue by DonYum** [sugyan/tensorflow-mnist#3]
Hi,
I think the src under static/js and static/css may be wrong.
I download these src from https://tensorflow-mnist.herokuapp.com/ manually.

**Comment by peachyDinosaur** [comment]
How do you fix it. Whenever I try to run locally or create manually, the thing breaks suggestions on how to fix this ?

**Comment by sugyan** [comment]
The static js file is generated by the following command:

```
$ npm install
```
