### ISSUE TITLE
Deploy to Heroku : Build Error

### ISSUE THREAD

**Issue by thecodeboy** [sugyan/tensorflow-mnist#4]
**Error:**
```
$ pip install -r requirements.txt
       tensorflow-0.11.0-cp35-cp35m-linux_x86_64.whl is not a supported wheel on this platform.
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Screenshot:**
![screenshot from 2017-02-09 16-36-10](https://cloud.githubusercontent.com/assets/10260999/22780765/e4262a0e-eee5-11e6-8af9-59f6aa18afb8.png)

**Comment by sugyan** [comment]
Sorry, it seems that the runtime version of Python and the wheel of TensorFlow did not match.
In Heroku, Python 3 seems to be able to use only python 3.6, so I modified it to fit Python 2.7.

- https://github.com/sugyan/tensorflow-mnist/commit/39669822385d29cf4b81da1d3708e1a65bf70e7a#diff-b4ef698db8ca845e5845c4618278f29aR16

Now you can deploy from the Heroku button successfully.
