### ISSUE TITLE
Cannot mannually deploy to heroku

### ISSUE THREAD

**Issue by peachyDinosaur** [sugyan/tensorflow-mnist#5]
After creating the app and trying to add 
$ heroku buildpacks:add heroku/nodejs
$ heroku buildpacks:add heroku/python
Both respond with app not found

**Comment by sugyan** [comment]
Maybe, you didn't specify app name.

```
$ heroku buildpacks:add heroku/nodejs --app APP
$ heroku buildpacks:add heroku/python --app APP
```

In this way, you may need to specify `APP`.
(This `APP` is generated by` heroku apps:create`)

see: https://devcenter.heroku.com/articles/using-the-cli

**Comment by peachyDinosaur** [comment]
my mistake there was no issue just me being new to heroku
