### ISSUE TITLE
not accurate in other digits such as ID cards's digits 

### ISSUE THREAD

**Issue by tengshaofeng** [sugyan/tensorflow-mnist#7]
hi,
   i am so appreciated with your work. but i use your model to test for my digit cuted from ID-cards.
it seams not accurate.

**Comment by tengshaofeng** [comment]
and my test code is:

```python
def digit_rec(filename):
    im = cv2.imread(filename, 0)
    im = cv2.resize(im, (28, 28))/255.0
    input = im.reshape(1, 784)
    # input = ((255 - np.array(request.json, dtype=np.uint8)) / 255.0).reshape(1, 784)
    output = convolutional(input)

    return output


if __name__ == '__main__':
    imgs_list = os.listdir('testimgs')
    for i in imgs_list:
        print i
        output = digit_rec(os.path.join('testimgs', i))
        print output
        print 'recognition:', np.argmax(output)
```

I need your help. what is the problem . thanks

**Comment by tengshaofeng** [comment]
[0.005912874359637499, 0.007515867240726948, 0.01965569145977497, 0.028222503140568733, 0.0036486987955868244, 0.017273299396038055, 0.38814234733581543, 0.016542382538318634, 0.5074454545974731, 0.005640867166221142]
is it according to [0,1, 2, ..., 9]???

**Comment by sugyan** [comment]
https://github.github.com/gfm/#fenced-code-blocks

**Comment by sugyan** [comment]
Yes, `np.argmax(output)` will output `8`. It is predicted digit.

**Comment by tengshaofeng** [comment]
but 8 is not correct. the actual digit is 3.  what is the problem. have you test your model in other digits except  minist.

**Comment by sugyan** [comment]
What is the image you input?
In `main.py`, I wrote `input` as below
```python
    input = ((255 - np.array(request.json, dtype=np.uint8)) / 255.0).reshape(1, 784)
```
This means inversion of black and white.
`model.regression` and `model.convolutional` treat input data as an image with **white foreground (1.0)** and **black background (0.0)**.
If you use the image with white background, you need to invert by `im = 1.0 - cv2.resize(im, (28, 28))/255.0`

**Comment by tengshaofeng** [comment]
thanks so much, 
you really solved my question.

**Comment by tengshaofeng** [comment]
hi @sugyan ,
a last question,
when train your convolutional model, 
data = input_data.read_data_sets("/tmp/data/", one_hot=True)
the path data  /tmp/data/ is loaded autoly by code? or it is the offline data shoud i load from web?

**Comment by sugyan** [comment]
`input_data.read_data_sets` will download data file from web if it doesn't exist.
Please see https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/contrib/learn/python/learn/datasets/mnist.py

**Comment by tengshaofeng** [comment]
thanks
